### ISSUE TITLE
PhpExecJs: Cannot autodetect any JavaScript runtime

### ISSUE THREAD

**Issue by timurozkul** [AlexandreKilian/craft-react#2]
I am not sure how set up the structure of the project, can I just add my react project to a /app ?  
The current error I am getting is 'PhpExecJs: Cannot autodetect any JavaScript runtime'
Working example would be great!

**Comment by magicspon** [comment]
I believe an example is on it's way
https://github.com/AlexandreKilian/craft-react/issues/1#issuecomment-424708579

**Comment by AlexandreKilian** [comment]
yes, an example is on the way… but that problem comes from the fact, that node couldnt be found locally… you must make sure that node is available for your host
@timurozkul are you by any chance opening it with MAMP or XAMP? I had problems with setting up the node environment there, I usually use 'client_side' to develop locally and open a server directly with PHP when trying to test server side by doing `php -S localhost:8000` in the `web` directory, that way, node is available…

I will try to document this in my upcoming example/documentation

**Comment by alexthegoodman** [comment]
@AlexandreKilian Looking forward to your example!
